[package]
name = "lief-sys"
version = "0.1.0"
authors = ["tathanhdinh <tathanhdinh@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]

[build-dependencies]
bindgen = { git = "https://github.com/rust-lang-nursery/rust-bindgen.git" }
cmake = "0.1.34"